# Generated by Django 4.1.4 on 2022-12-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_hours_of_screening_screening_screening_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='hall_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
