# Generated by Django 4.1.2 on 2022-12-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_hall_hall_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='tickets_left',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
